version: "3.8"

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: counter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: python:3.9-slim
    container_name: web_server
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: counter_db
    command: >
      sh -c "pip install flask mysql-connector-python &&
      python app.py"

volumes:
  mysql_data:
